FROM node:16-alpine as build
# Set working directory
WORKDIR /app
# Copy the package. json and install dependencies
COPY package*.json ./ RUN npm install --silent
# Copy the app source code and build it
COPY • •
RUN pm run build
# Stage 2: Serve the app using Nginx
FROM nginx:alpine
# Copy the React build from the previous stage
COPY --from=build /app/build /usr/share/nginx/html
# Expose port 80
EXPOSE 80
# Command to run Nginx
MD ["nginx", "-g", "daemon off;"]