apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-api-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-api-app
  template:
    metadata:
      labels:
        app: flask-api-app
    spec:
      containers:
      - name: flask-api-app
        image: gcr.io/ds-assignment-1-438201/assignment1-flask-api-app 
        ports:
        - containerPort: 8080
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.29.0
        command: ["/cloud_sql_proxy",
                  "-instances=ds-assignment-1-438201:us-central1:admin",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
        - name: cloudsql-secrets
          mountPath: /secrets/cloudsql
volumes:
    - name: cloudsql-secrets
      secret:
        secretName: cloudsql-instance-credentials